{
  default:graphqlTestSortedView {
    results {
      entityLabel
    }
  }

  asc:graphqlTestSortedView(sortBy: title) {
    results {
      entityLabel
    }
  }

  desc:graphqlTestSortedView(sortBy: title, sortDirection: desc) {
    results {
      entityLabel
    }
  }

  asc_nid:graphqlTestSortedView(sortBy: nid, sortDirection: asc) {
    results {
      entityLabel
    }
  }

  desc_nid:graphqlTestSortedView(sortBy: nid, sortDirection: desc) {
    results {
      entityLabel
    }
  }
}